"""add created_at to transactions

Revision ID: ffc86c70f4cc
Revises: 03d57a90ab3e
Create Date: 2026-09-03 21:28:33.186668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc86c70f4cc'
down_revision: Union[str, Sequence[str], None] = '03d57a90ab3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'transactions',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE transactions SET created_at = CURRENT_TIMESTAMP"
    )

    op.alter_column(
        'transactions',
        'created_at',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
